### ISSUE TITLE
Fix the scene lights to have the same prioperties when turning them off and on again.

### ISSUE THREAD

**Issue by originalnicodr** [originalnicodr/RELit#6]
For some reason, once you switch off all the scene lights and turn them back on again they don't return as they originally were, but with increased intensity? This might be because we are not really using a method to disable the lights but modifying the memory of each light, so it might be some sort of unexpected behavior going on in there.

We should keep our eyes open to alternative ways of doing this to see if we can avoid this problem.

Original scene lights:
![image](https://user-images.githubusercontent.com/24371572/177024666-b946fc51-69e9-448a-b040-7c9c91c1b4e6.png)

Scene lights after turning them off and on again:
![image](https://user-images.githubusercontent.com/24371572/177024670-9cb181f6-ac75-4cd9-b828-81094dcb3c7b.png)

**Comment by FransBouma** [comment]
This has been fixed in 1.1.3
